url: "https://pt.beep.vip" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/pter" # the subpath of your site, e.g. /blog

title: 'pter'

theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-spaceship
  - jekyll-seo-tag
  - jekyll-admin
  - jemoji


